La til endring i workflow som fikser feil i bygg og endret plassering av localwiremocksmoketest file.

diff --git a/.github/workflows/code-quality.yml b/.github/workflows/code-quality.yml
--- a/.github/workflows/code-quality.yml
+++ b/.github/workflows/code-quality.yml
@@ -47,4 +47,10 @@ jobs:
         run: chmod +x ./gradlew
 
       - name: Kjør bygg
-        run: ./gradlew build
+        run: |
+            for attempt in 1 2 3; do
+              ./gradlew build && exit 0
+              echo "Attempt $attempt failed. Waiting 30s before retry..."
+              sleep 30
+            done
+            exit 1
